server:
  port: 8080

openapi:
  base-url: "https://apis.data.go.kr"
  job-list-path: "/B552583/job/job_list_env"
  # 환경변수 우선: OPENAPI_SERVICE_KEY_DECODING, 없으면 기본값 사용
  service-key-decoding: "${548fae30514b3af63e44b662142f18ecd387a8cb6092a1f3452f3b293ff1026c}"

fastapi:
  base-url: "http://localhost:8000"   # 배포 시 프로필/환경변수로 분리 권장

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heart_db?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: root
    password: "admin"
    driver-class-name: com.mysql.cj.jdbc.Driver
    # (선택) Hikari 튜닝
    # hikari:
    #   maximum-pool-size: 10
    #   minimum-idle: 5
    #   idle-timeout: 30000
    #   connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none         # 초기엔 validate, 운영은 none 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # (선택) 배치 성능
        # jdbc.batch_size: 50
        # order_inserts: true
        # order_updates: true
    database-platform: org.hibernate.dialect.MySQLDialect  # Hibernate 6 권장

  thymeleaf:
    cache: false  # 개발 편의

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # Hibernate 6 바인딩 로깅

springdoc:
  packages-to-scan: com.test
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /practice-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

resilience4j:
  circuitbreaker:
    instances:
      fastapi:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      fastapi:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2.0
  timelimiter:
    instances:
      fastapi:
        timeout-duration: 800ms
